#!/usr/bin/env python2.7
# coding: utf-8

import string

cipher = "ZNKIGKYGXIOVNKXOYGXKGRREURJIOVNKXCNOINOYXKGRRECKGQOSTUZYAXKNUCURJHKIG\
AYKOSZUURGFEZURUUQGZZNKCOQOVGMKGZZNKSUSKTZHAZOLOMAXKOZYMUZZUHKGZRKGYZROQKLOLZEE\
KGXYURJUXCNGZKBKXBGPJADLIVBAYKZNUYKRGYZZKTINGXGIZKXYGYZNKYURAZOUT"

charsetlen = len(string.uppercase)
ascii_offset = 65

for i in xrange(charsetlen):
    print '[+] Key : {}'.format(chr(i + ascii_offset))
    print ''.join(map(lambda x:chr(((ord(x)-ascii_offset+i)%charsetlen)+ascii_offset),cipher))
    print '\n'

# THE CAESAR CIPHER IS A REALLY OLD CIPHER WHICH IS REALLY WEAK IM NOT SURE HOW
# OLD BECAUSE IM TOO LAZY TO LOOK AT THE WIKI PAGE AT THE MOMENT BUT I FIGURE ITS
# GOT TO BE AT LEAST LIKE FIFTY YEARS OLD OR WHATEVER VAJDUXFCPV USE THOSE LAST
# TEN CHARACTERS AS THE SOLUTION
